"""initial migration

Revision ID: adc4bacd3cae
Revises: 
Create Date: 2025-07-16 05:33:57.704122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'adc4bacd3cae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coin_wallets')
    op.drop_table('user_achievements')
    op.drop_table('auto_replies')
    op.drop_table('gift_milestones')
    op.drop_table('stream_reports')
    op.drop_index('ix_chat_messages_id', table_name='chat_messages')
    op.drop_index('ix_chat_messages_room_id', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('ix_filters_id', table_name='filters')
    op.drop_table('filters')
    op.drop_index('ix_replay_captions_id', table_name='replay_captions')
    op.drop_table('replay_captions')
    op.drop_table('ai_recommendations')
    op.drop_table('price_suggestions')
    op.drop_index('ix_replay_titles_id', table_name='replay_titles')
    op.drop_table('replay_titles')
    op.drop_index('ix_replay_analytics_id', table_name='replay_analytics')
    op.drop_table('replay_analytics')
    op.drop_index('ix_gift_fly_id', table_name='gift_fly')
    op.drop_table('gift_fly')
    op.drop_table('live_goals')
    op.drop_table('moderation_logs')
    op.drop_table('leaderboard_entries')
    op.drop_index('ix_viewers_id', table_name='viewers')
    op.drop_table('viewers')
    op.drop_table('scheduled_streams')
    op.drop_table('gift_requests')
    op.drop_table('stream_captions')
    op.drop_index('ix_share_activities_id', table_name='share_activities')
    op.drop_index('ix_share_activities_room_id', table_name='share_activities')
    op.drop_index('ix_share_activities_user_id', table_name='share_activities')
    op.drop_table('share_activities')
    op.drop_table('stream_ratings')
    op.drop_table('wallets')
    op.drop_table('experiment_flags')
    op.drop_index('ix_live_viewers_id', table_name='live_viewers')
    op.drop_table('live_viewers')
    op.drop_table('fan_clubs')
    op.drop_table('withdraw_requests')
    op.drop_table('live_product_logs')
    op.drop_table('download_requests')
    op.drop_table('ai_user_profile')
    op.drop_index('ix_cohost_invitations_id', table_name='cohost_invitations')
    op.drop_index('ix_cohost_invitations_receiver_id', table_name='cohost_invitations')
    op.drop_index('ix_cohost_invitations_sender_id', table_name='cohost_invitations')
    op.drop_table('cohost_invitations')
    op.drop_index('ix_leaderboard_notifications_id', table_name='leaderboard_notifications')
    op.drop_table('leaderboard_notifications')
    op.drop_index('ix_gift_markers_id', table_name='gift_markers')
    op.drop_table('gift_markers')
    op.drop_index('ix_announcements_id', table_name='announcements')
    op.drop_table('announcements')
    op.drop_table('community_impact')
    op.drop_table('referrals')
    op.drop_table('video_analysis')
    op.drop_table('learning_sessions')
    op.drop_index('ix_moderation_actions_id', table_name='moderation_actions')
    op.drop_index('ix_moderation_actions_room_id', table_name='moderation_actions')
    op.drop_table('moderation_actions')
    op.drop_table('user_goals')
    op.drop_index('ix_live_products_id', table_name='live_products')
    op.drop_index('ix_live_products_room_id', table_name='live_products')
    op.drop_table('live_products')
    op.drop_index('ix_likes_id', table_name='likes')
    op.drop_index('ix_likes_stream_id', table_name='likes')
    op.drop_table('likes')
    op.drop_index('ix_push_subscriptions_id', table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    op.drop_index('ix_fans_id', table_name='fans')
    op.drop_table('fans')
    op.drop_table('replay_markers')
    op.drop_table('fraud_flags')
    op.drop_table('user_notifications')
    op.drop_index('ix_superchats_id', table_name='superchats')
    op.drop_table('superchats')
    op.drop_table('live_polls')
    op.drop_index('ix_top_contributors_id', table_name='top_contributors')
    op.drop_table('top_contributors')
    op.drop_table('live_moderation_actions')
    op.drop_table('gift_transactions')
    op.drop_table('wallet_transactions')
    op.drop_table('stream_clips')
    op.drop_index('ix_smart_replies_id', table_name='smart_replies')
    op.drop_index('ix_smart_replies_room_id', table_name='smart_replies')
    op.drop_table('smart_replies')
    op.drop_index('ix_replay_summaries_id', table_name='replay_summaries')
    op.drop_table('replay_summaries')
    op.drop_table('smart_receipts')
    op.drop_table('stream_viewer_events')
    op.drop_table('push_notifications')
    op.drop_index('ix_co_host_invites_stream_id', table_name='co_host_invites')
    op.drop_column('co_host_invites', 'stream_id')
    op.add_column('co_host_invites', sa.Column('live_stream_id', sa.Integer(), nullable=False))
    op.create_foreign_key(
        None,
        source_table='co_host_invites',
        referent_table='live_streams',
        local_cols=['live_stream_id'],
        remote_cols=['id']
    )

    # === Modify co_hosts.stream_id: change to INTEGER with safe casting ===
    op.execute("ALTER TABLE co_hosts ALTER COLUMN stream_id TYPE INTEGER USING stream_id::INTEGER")

    # === Ensure co_hosts.user_id is NOT NULL ===
    op.alter_column(
        'co_hosts', 'user_id',
        existing_type=sa.INTEGER(),
        nullable=False
    )

    # === Rebuild co_hosts.stream_id → live_streams.id foreign key ===
    op.drop_index('ix_co_hosts_stream_id', table_name='co_hosts')
    op.create_foreign_key(
        None,
        source_table='co_hosts',
        referent_table='live_streams',
        local_cols=['stream_id'],
        remote_cols=['id']
    )

    # === Clean up live_streams indexes & constraints ===
    op.drop_index('ix_live_streams_host_id', table_name='live_streams')
    op.drop_index('ix_live_streams_room_id', table_name='live_streams')
    op.create_unique_constraint(None, 'live_streams', ['code'])
    op.drop_constraint('live_streams_top_fan_id_fkey', 'live_streams', type_='foreignkey')
    op.drop_constraint('live_streams_ended_by_fkey', 'live_streams', type_='foreignkey')
    op.drop_column('live_streams', 'superchat_enabled')

    op.drop_column('live_streams', 'recent_gifts')
    op.drop_column('live_streams', 'goal_target')
    op.drop_column('live_streams', 'max_attendees')
    op.drop_column('live_streams', 'ai_host_personality')
    op.drop_column('live_streams', 'is_gift_active')
    op.drop_column('live_streams', 'location_name')
    op.drop_column('live_streams', 'camera_toggle_history')
    op.drop_column('live_streams', 'challenge_active')
    op.drop_column('live_streams', 'active_cohosts')
    op.drop_column('live_streams', 'is_safe_mode')
    op.drop_column('live_streams', 'mic_enabled')
    op.drop_column('live_streams', 'sig_injected_metadata')
    op.drop_column('live_streams', 'combo_streak')
    op.drop_column('live_streams', 'end_live_reason')
    op.drop_column('live_streams', 'ended_by')
    op.drop_column('live_streams', 'replay_marker_time')
    op.drop_column('live_streams', 'highlight_quotes')
    op.drop_column('live_streams', 'has_replay')
    op.drop_column('live_streams', 'guest_requests')
    op.drop_column('live_streams', 'auto_recording_url')
    op.drop_column('live_streams', 'pinned_comment')
    op.drop_column('live_streams', 'camera_enabled')
    op.drop_column('live_streams', 'host_energy_level')
    op.drop_column('live_streams', 'sig_command_queue')
    op.drop_column('live_streams', 'is_verified_host_voice')
    op.drop_column('live_streams', 'engagement_score')
    op.drop_column('live_streams', 'camera_toggle_log')
    op.drop_column('live_streams', 'share_count')
    op.drop_column('live_streams', 'show_gift_drawer')
    op.drop_column('live_streams', 'total_view_time')
    op.drop_column('live_streams', 'ticket_price')
    op.drop_column('live_streams', 'top_fan_id')
    op.drop_column('live_streams', 'ai_host_memory')
    op.drop_column('live_streams', 'goal_type')
    op.drop_column('live_streams', 'sig_last_sync_at')
    op.drop_column('live_streams', 'sig_intelligence_score')
    op.drop_column('live_streams', 'topic')
    op.drop_column('live_streams', 'leaderboard')
    op.drop_column('live_streams', 'replay_url')
    op.drop_column('live_streams', 'milestone_achieved')
    op.drop_column('live_streams', 'host_id')
    op.drop_column('live_streams', 'total_gift_value')
    op.drop_column('live_streams', 'troll_flagged_users')
    op.drop_column('live_streams', 'goal_progress')
    op.drop_column('live_streams', 'ai_host_response')
    op.drop_column('live_streams', 'guest_layout_mode')
    op.drop_column('live_streams', 'superchat_count')
    op.drop_column('live_streams', 'latest_superchats')
    op.drop_column('live_streams', 'gift_animation_position')
    op.drop_column('live_streams', 'is_ticketed')
    op.drop_column('live_streams', 'is_under_spam_watch')
    op.drop_column('live_streams', 'is_ai_host_enabled')
    op.drop_column('live_streams', 'sig_control_level')
    op.drop_column('live_streams', 'is_live')
    op.drop_column('live_streams', 'combo_last_gift_id')
    op.drop_column('live_streams', 'is_parental_control_enabled')
    op.drop_column('live_streams', 'ai_tags_suggested')
    op.drop_column('live_streams', 'sig_knowledge_links')
    op.drop_column('live_streams', 'challenge_target')
    op.drop_column('live_streams', 'sig_predicted_outcome')
    op.drop_column('live_streams', 'countdown_to')
    op.drop_column('live_streams', 'sig_auto_feedback')
    op.drop_column('live_streams', 'gift_combo_active')
    op.drop_column('live_streams', 'total_gifts_received')
    op.drop_column('live_streams', 'host_status')
    op.drop_column('live_streams', 'guest_approved')
    op.drop_column('live_streams', 'is_camera_enabled')
    op.drop_column('live_streams', 'sig_auto_event_trigger')
    op.drop_column('live_streams', 'stream_theme')
    op.drop_column('live_streams', 'challenge_progress')
    op.drop_column('live_streams', 'spam_score')
    op.drop_column('live_streams', 'ai_host_replies')
    op.drop_column('live_streams', 'sig_debug_mode')
    op.drop_column('live_streams', 'replay_highlights')
    op.drop_column('live_streams', 'like_history')
    op.drop_column('live_streams', 'voice_signature_hash')
    op.drop_column('live_streams', 'sig_memory_snapshot')
    op.drop_column('live_streams', 'screen_sharing_enabled')
    op.drop_column('live_streams', 'age_rating')
    op.drop_column('live_streams', 'gift_queue')
    op.drop_column('live_streams', 'is_like_active')
    op.drop_column('live_streams', 'has_countdown')
    op.drop_column('live_streams', 'sig_strategy_notes')
    op.drop_column('live_streams', 'ai_voice_profile')
    op.drop_column('live_streams', 'mic_toggle_history')
    op.drop_column('live_streams', 'milestone_type')
    op.drop_column('live_streams', 'sig_last_command')
    op.drop_column('live_streams', 'sig_internal_flags')
    op.drop_column('live_streams', 'is_share_disabled')
    op.drop_column('live_streams', 'ai_host_enabled')
    op.drop_column('live_streams', 'active_guests')
    op.drop_column('live_streams', 'challenge_type')
    op.drop_column('live_streams', 'viewer_sessions')
    op.drop_column('live_streams', 'camera_permission_status')
    op.drop_column('live_streams', 'is_microphone_enabled')
    op.drop_column('live_streams', 'total_likes')
    op.drop_column('live_streams', 'sig_override_reason')
    op.drop_column('live_streams', 'is_force_ended')
    op.drop_column('live_streams', 'ai_host_name')
    op.drop_column('live_streams', 'is_hidden_from_users')
    op.drop_column('live_streams', 'sig_last_comm_status')
    op.drop_column('live_streams', 'ai_summary_text')
    op.drop_column('live_streams', 'sig_mission_type')
    op.drop_column('live_streams', 'gift_effect_url')
    op.drop_column('live_streams', 'room_id')
    op.drop_column('live_streams', 'current_gift')
    op.drop_column('live_streams', 'is_sig_controlled')
    op.drop_column('live_streams', 'sig_comm_log')
    op.drop_column('live_streams', 'guest_grid_layout')
    op.drop_column('live_streams', 'peak_viewers')
    op.drop_column('live_streams', 'combo_expires_at')
    op.drop_column('live_streams', 'milestone_targets')
    op.drop_column('live_streams', 'ai_chat_history')
    op.drop_column('live_streams', 'sig_only_visibility')
    op.drop_column('live_streams', 'top_gift_name')
    op.drop_column('live_streams', 'sig_logs')
    op.drop_column('live_streams', 'tags')
    op.drop_column('live_streams', 'guest_history')
    op.drop_column('live_streams', 'current_gift_effect')
    op.drop_column('live_streams', 'snapshot_url')
    op.drop_column('live_streams', 'shared_by')
    op.drop_column('live_streams', 'location_coords')
    op.add_column('message_logs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'message_logs', 'users', ['user_id'], ['id'])
    op.drop_column('message_logs', 'sender')
    op.add_column('referral_bonuses', sa.Column('referrer_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'referral_bonuses', 'users', ['referrer_id'], ['id'], ondelete='CASCADE')
    op.add_column('referral_logs', sa.Column('referrer_id', sa.Integer(), nullable=False))
    op.add_column('referral_logs', sa.Column('referred_user_id', sa.Integer(), nullable=False))
    op.alter_column('referral_logs', 'product_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('referral_logs', 'buyer_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('referral_logs', 'amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('referral_logs_promoter_id_fkey', 'referral_logs', type_='foreignkey')
    op.create_foreign_key(None, 'referral_logs', 'users', ['referred_user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'referral_logs', 'users', ['referrer_id'], ['id'], ondelete='CASCADE')
    op.drop_column('referral_logs', 'promoter_id')
    op.add_column('users', sa.Column('profile_image', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.drop_column('users', 'admin_task')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('admin_task', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'profile_image')
    op.add_column('referral_logs', sa.Column('promoter_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'referral_logs', type_='foreignkey')
    op.drop_constraint(None, 'referral_logs', type_='foreignkey')
    op.create_foreign_key('referral_logs_promoter_id_fkey', 'referral_logs', 'users', ['promoter_id'], ['id'], ondelete='CASCADE')
    op.alter_column('referral_logs', 'amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('referral_logs', 'buyer_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('referral_logs', 'product_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('referral_logs', 'referred_user_id')
    op.drop_column('referral_logs', 'referrer_id')
    op.drop_constraint(None, 'referral_bonuses', type_='foreignkey')
    op.drop_column('referral_bonuses', 'referrer_id')
    op.add_column('message_logs', sa.Column('sender', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'message_logs', type_='foreignkey')
    op.drop_column('message_logs', 'user_id')
    op.add_column('live_streams', sa.Column('location_coords', sa.NullType(), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('shared_by', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('snapshot_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('current_gift_effect', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('guest_history', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('tags', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('sig_logs', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('top_gift_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('sig_only_visibility', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('ai_chat_history', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('milestone_targets', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('combo_expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('peak_viewers', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('guest_grid_layout', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('sig_comm_log', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('is_sig_controlled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('current_gift', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('room_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('gift_effect_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('sig_mission_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('ai_summary_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('sig_last_comm_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('is_hidden_from_users', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('ai_host_name', sa.VARCHAR(length=100), server_default=sa.text("'Smart Host'::character varying"), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('is_force_ended', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('sig_override_reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('total_likes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('is_microphone_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('camera_permission_status', sa.VARCHAR(length=50), server_default=sa.text("'granted'::character varying"), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('viewer_sessions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('challenge_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('active_guests', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('ai_host_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('is_share_disabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('sig_internal_flags', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('sig_last_command', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('milestone_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('mic_toggle_history', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('ai_voice_profile', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('sig_strategy_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('has_countdown', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('is_like_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('gift_queue', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('age_rating', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('screen_sharing_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('sig_memory_snapshot', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('voice_signature_hash', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('like_history', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('replay_highlights', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('sig_debug_mode', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('ai_host_replies', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('spam_score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('challenge_progress', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('stream_theme', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('sig_auto_event_trigger', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('is_camera_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('guest_approved', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('host_status', sa.VARCHAR(length=50), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('total_gifts_received', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('gift_combo_active', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('sig_auto_feedback', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('countdown_to', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('sig_predicted_outcome', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('challenge_target', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('sig_knowledge_links', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('ai_tags_suggested', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('is_parental_control_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('combo_last_gift_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('is_live', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('sig_control_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('is_ai_host_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('is_under_spam_watch', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('is_ticketed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('gift_animation_position', sa.TEXT(), server_default=sa.text("'center'::text"), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('latest_superchats', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('superchat_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('guest_layout_mode', sa.VARCHAR(length=50), server_default=sa.text("'grid'::character varying"), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('ai_host_response', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('goal_progress', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('troll_flagged_users', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('total_gift_value', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('host_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('milestone_achieved', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('replay_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('leaderboard', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('topic', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('sig_intelligence_score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('sig_last_sync_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('goal_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('ai_host_memory', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('top_fan_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('ticket_price', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('total_view_time', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('show_gift_drawer', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('share_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('camera_toggle_log', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('engagement_score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('is_verified_host_voice', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('sig_command_queue', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('host_energy_level', sa.INTEGER(), server_default=sa.text('100'), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('camera_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('pinned_comment', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('auto_recording_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('guest_requests', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('has_replay', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('highlight_quotes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('replay_marker_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('ended_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('end_live_reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('combo_streak', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('sig_injected_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('mic_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('is_safe_mode', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('active_cohosts', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('challenge_active', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('camera_toggle_history', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('location_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('is_gift_active', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('ai_host_personality', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('max_attendees', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('goal_target', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('recent_gifts', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('live_streams', sa.Column('superchat_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.create_foreign_key('live_streams_ended_by_fkey', 'live_streams', 'users', ['ended_by'], ['id'])
    op.create_foreign_key('live_streams_top_fan_id_fkey', 'live_streams', 'users', ['top_fan_id'], ['id'])
    op.drop_constraint(None, 'live_streams', type_='unique')
    op.create_index('ix_live_streams_room_id', 'live_streams', ['room_id'], unique=True)
    op.create_index('ix_live_streams_host_id', 'live_streams', ['host_id'], unique=False)
    op.drop_constraint(None, 'co_hosts', type_='foreignkey')
    op.create_index('ix_co_hosts_stream_id', 'co_hosts', ['stream_id'], unique=False)
    op.alter_column('co_hosts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('co_hosts', 'stream_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.add_column('co_host_invites', sa.Column('stream_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'co_host_invites', type_='foreignkey')
    op.create_index('ix_co_host_invites_stream_id', 'co_host_invites', ['stream_id'], unique=False)
    op.drop_column('co_host_invites', 'live_stream_id')
    op.create_table('push_notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sent_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='push_notifications_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='push_notifications_pkey')
    )
    op.create_table('stream_viewer_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stream_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('device_info', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['stream_id'], ['live_streams.id'], name='stream_viewer_events_stream_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='stream_viewer_events_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stream_viewer_events_pkey')
    )
    op.create_table('smart_receipts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='smart_receipts_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='smart_receipts_pkey')
    )
    op.create_table('replay_summaries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stream_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('summary_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['stream_id'], ['live_streams.id'], name='replay_summaries_stream_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='replay_summaries_pkey')
    )
    op.create_index('ix_replay_summaries_id', 'replay_summaries', ['id'], unique=False)
    op.create_table('smart_replies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='smart_replies_pkey')
    )
    op.create_index('ix_smart_replies_room_id', 'smart_replies', ['room_id'], unique=False)
    op.create_index('ix_smart_replies_id', 'smart_replies', ['id'], unique=False)
    op.create_table('stream_clips',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stream_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('clip_start', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('clip_end', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['stream_id'], ['live_streams.id'], name='stream_clips_stream_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='stream_clips_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stream_clips_pkey')
    )
    op.create_table('wallet_transactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('reference_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='wallet_transactions_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='wallet_transactions_pkey')
    )
    op.create_table('gift_transactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stream_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gift_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('coin_spent', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sent_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['gift_id'], ['gifts.id'], name='gift_transactions_gift_id_fkey'),
    sa.ForeignKeyConstraint(['stream_id'], ['live_streams.id'], name='gift_transactions_stream_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='gift_transactions_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='gift_transactions_pkey')
    )
    op.create_table('live_moderation_actions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stream_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('target_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action_type', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['stream_id'], ['live_streams.id'], name='live_moderation_actions_stream_id_fkey'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], name='live_moderation_actions_target_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='live_moderation_actions_pkey')
    )
    op.create_table('top_contributors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stream_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_value', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['stream_id'], ['live_streams.id'], name='top_contributors_stream_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='top_contributors_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='top_contributors_pkey')
    )
    op.create_index('ix_top_contributors_id', 'top_contributors', ['id'], unique=False)
    op.create_table('live_polls',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stream_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('options', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('results', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['stream_id'], ['live_streams.id'], name='live_polls_stream_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='live_polls_pkey')
    )
    op.create_table('superchats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stream_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('emoji', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('animation_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('voice_clip_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('highlight_color', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='superchats_pkey')
    )
    op.create_index('ix_superchats_id', 'superchats', ['id'], unique=False)
    op.create_table('user_notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notif_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_notifications_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_notifications_pkey')
    )
    op.create_table('fraud_flags',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('issue_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('flagged_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fraud_flags_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='fraud_flags_pkey')
    )
    op.create_table('replay_markers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stream_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['stream_id'], ['live_streams.id'], name='replay_markers_stream_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='replay_markers_pkey')
    )
    op.create_table('fans',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('host_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_contribution', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('last_contributed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], name='fans_host_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fans_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='fans_pkey')
    )
    op.create_index('ix_fans_id', 'fans', ['id'], unique=False)
    op.create_table('push_subscriptions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('endpoint', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('p256dh', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('auth', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='push_subscriptions_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='push_subscriptions_pkey'),
    sa.UniqueConstraint('endpoint', name='push_subscriptions_endpoint_key')
    )
    op.create_index('ix_push_subscriptions_id', 'push_subscriptions', ['id'], unique=False)
    op.create_table('likes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stream_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='likes_pkey')
    )
    op.create_index('ix_likes_stream_id', 'likes', ['stream_id'], unique=False)
    op.create_index('ix_likes_id', 'likes', ['id'], unique=False)
    op.create_table('live_products',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('showcased_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='live_products_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='live_products_pkey')
    )
    op.create_index('ix_live_products_room_id', 'live_products', ['room_id'], unique=False)
    op.create_index('ix_live_products_id', 'live_products', ['id'], unique=False)
    op.create_table('user_goals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('host_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('target_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('current_amount', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('supporters', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], name='user_goals_host_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_goals_pkey')
    )
    op.create_table('moderation_actions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('target_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('moderator_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action', postgresql.ENUM('mute', 'block', 'report', name='actiontype'), autoincrement=False, nullable=True),
    sa.Column('reason', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='moderation_actions_pkey')
    )
    op.create_index('ix_moderation_actions_room_id', 'moderation_actions', ['room_id'], unique=False)
    op.create_index('ix_moderation_actions_id', 'moderation_actions', ['id'], unique=False)
    op.create_table('learning_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('topic', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('host_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_ai_session', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], name='learning_sessions_host_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='learning_sessions_pkey')
    )
    op.create_table('video_analysis',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stream_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ai_caption', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('auto_hashtags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['stream_id'], ['live_streams.id'], name='video_analysis_stream_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='video_analysis_pkey')
    )
    op.create_table('referrals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('referrer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('referred_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bonus_coins', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('referred_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['referred_id'], ['users.id'], name='referrals_referred_id_fkey'),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], name='referrals_referrer_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='referrals_pkey')
    )
    op.create_table('community_impact',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='community_impact_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='community_impact_pkey')
    )
    op.create_table('announcements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='announcements_pkey')
    )
    op.create_index('ix_announcements_id', 'announcements', ['id'], unique=False)
    op.create_table('gift_markers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stream_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('gift_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['stream_id'], ['live_streams.id'], name='gift_markers_stream_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='gift_markers_pkey')
    )
    op.create_index('ix_gift_markers_id', 'gift_markers', ['id'], unique=False)
    op.create_table('leaderboard_notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stream_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('previous_position', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('seen', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['stream_id'], ['live_streams.id'], name='leaderboard_notifications_stream_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='leaderboard_notifications_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='leaderboard_notifications_pkey')
    )
    op.create_index('ix_leaderboard_notifications_id', 'leaderboard_notifications', ['id'], unique=False)
    op.create_table('cohost_invitations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stream_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receiver_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['stream_id'], ['live_streams.id'], name='cohost_invitations_stream_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='cohost_invitations_pkey')
    )
    op.create_index('ix_cohost_invitations_sender_id', 'cohost_invitations', ['sender_id'], unique=False)
    op.create_index('ix_cohost_invitations_receiver_id', 'cohost_invitations', ['receiver_id'], unique=False)
    op.create_index('ix_cohost_invitations_id', 'cohost_invitations', ['id'], unique=False)
    op.create_table('ai_user_profile',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('behavior_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ai_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='ai_user_profile_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ai_user_profile_pkey')
    )
    op.create_table('download_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stream_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('format', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('requested_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['stream_id'], ['live_streams.id'], name='download_requests_stream_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='download_requests_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='download_requests_pkey')
    )
    op.create_table('live_product_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stream_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('displayed_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('duration_shown', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('clicks', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='live_product_logs_product_id_fkey'),
    sa.ForeignKeyConstraint(['stream_id'], ['live_streams.id'], name='live_product_logs_stream_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='live_product_logs_pkey')
    )
    op.create_table('withdraw_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('requested_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('is_paid', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('approved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('payment_reference', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='withdraw_requests_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='withdraw_requests_pkey')
    )
    op.create_table('fan_clubs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('host_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], name='fan_clubs_host_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='fan_clubs_pkey')
    )
    op.create_table('live_viewers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stream_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('joined_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('left_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['stream_id'], ['live_streams.id'], name='live_viewers_stream_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='live_viewers_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='live_viewers_pkey')
    )
    op.create_index('ix_live_viewers_id', 'live_viewers', ['id'], unique=False)
    op.create_table('experiment_flags',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('experiment_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('variant', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('assigned_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='experiment_flags_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='experiment_flags_pkey')
    )
    op.create_table('wallets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('coin_balance', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True),
    sa.Column('recharge_history', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('last_recharge_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('payment_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='wallets_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='wallets_pkey'),
    sa.UniqueConstraint('user_id', name='wallets_user_id_key')
    )
    op.create_table('stream_ratings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stream_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='stream_ratings_rating_check'),
    sa.ForeignKeyConstraint(['stream_id'], ['live_streams.id'], name='stream_ratings_stream_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='stream_ratings_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stream_ratings_pkey')
    )
    op.create_table('share_activities',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('room_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('platform', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('shared_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='share_activities_pkey')
    )
    op.create_index('ix_share_activities_user_id', 'share_activities', ['user_id'], unique=False)
    op.create_index('ix_share_activities_room_id', 'share_activities', ['room_id'], unique=False)
    op.create_index('ix_share_activities_id', 'share_activities', ['id'], unique=False)
    op.create_table('stream_captions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stream_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('language_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('caption_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['stream_id'], ['live_streams.id'], name='stream_captions_stream_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stream_captions_pkey')
    )
    op.create_table('gift_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='gift_requests_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='gift_requests_pkey')
    )
    op.create_table('scheduled_streams',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('host_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('scheduled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_notified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], name='scheduled_streams_host_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='scheduled_streams_pkey')
    )
    op.create_table('viewers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stream_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('joined_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='viewers_pkey')
    )
    op.create_index('ix_viewers_id', 'viewers', ['id'], unique=False)
    op.create_table('leaderboard_entries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('period', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('score', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('badge', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='leaderboard_entries_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='leaderboard_entries_pkey')
    )
    op.create_table('moderation_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stream_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('flagged_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('reason', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('action_taken', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['stream_id'], ['live_streams.id'], name='moderation_logs_stream_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='moderation_logs_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='moderation_logs_pkey')
    )
    op.create_table('live_goals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stream_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('goal_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('target_value', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('current_value', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('is_completed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['stream_id'], ['live_streams.id'], name='live_goals_stream_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='live_goals_pkey')
    )
    op.create_table('gift_fly',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stream_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gift_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='gift_fly_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='gift_fly_pkey')
    )
    op.create_index('ix_gift_fly_id', 'gift_fly', ['id'], unique=False)
    op.create_table('replay_analytics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stream_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('views', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comments', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('shares', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('downloads', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['stream_id'], ['live_streams.id'], name='replay_analytics_stream_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='replay_analytics_pkey')
    )
    op.create_index('ix_replay_analytics_id', 'replay_analytics', ['id'], unique=False)
    op.create_table('replay_titles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stream_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generated_title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['stream_id'], ['live_streams.id'], name='replay_titles_stream_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='replay_titles_pkey')
    )
    op.create_index('ix_replay_titles_id', 'replay_titles', ['id'], unique=False)
    op.create_table('price_suggestions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('current_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('suggested_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('generated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='price_suggestions_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='price_suggestions_pkey')
    )
    op.create_table('ai_recommendations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recommended_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('reference_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='ai_recommendations_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ai_recommendations_pkey')
    )
    op.create_table('replay_captions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stream_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['stream_id'], ['live_streams.id'], name='replay_captions_stream_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='replay_captions_pkey')
    )
    op.create_index('ix_replay_captions_id', 'replay_captions', ['id'], unique=False)
    op.create_table('filters',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('css_class', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='filters_pkey'),
    sa.UniqueConstraint('name', name='filters_name_key'),
    sa.UniqueConstraint('slug', name='filters_slug_key')
    )
    op.create_index('ix_filters_id', 'filters', ['id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('room_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name='chat_messages_sender_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='chat_messages_pkey')
    )
    op.create_index('ix_chat_messages_room_id', 'chat_messages', ['room_id'], unique=False)
    op.create_index('ix_chat_messages_id', 'chat_messages', ['id'], unique=False)
    op.create_table('stream_reports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('reporter_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reported_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stream_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('reported_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['reported_user_id'], ['users.id'], name='stream_reports_reported_user_id_fkey'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], name='stream_reports_reporter_id_fkey'),
    sa.ForeignKeyConstraint(['stream_id'], ['live_streams.id'], name='stream_reports_stream_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stream_reports_pkey')
    )
    op.create_table('gift_milestones',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gift_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('last_triggered', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['gift_id'], ['gifts.id'], name='gift_milestones_gift_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='gift_milestones_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='gift_milestones_pkey')
    )
    op.create_table('auto_replies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('trigger_keywords', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('reply_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='auto_replies_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='auto_replies_pkey')
    )
    op.create_table('user_achievements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('badge_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('badge_icon', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('awarded_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_achievements_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_achievements_pkey')
    )
    op.create_table('coin_wallets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('balance', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='coin_wallets_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='coin_wallets_pkey'),
    sa.UniqueConstraint('user_id', name='coin_wallets_user_id_key')
    )
    # ### end Alembic commands ###
